export class Prospect {
    prospectId:String;
    firstName:String;
    lastName:String;
    address:String;
    loanType:String;
    income:Number;
    requiredLoanAmt:Number;
    panNumber:String;
    aadharNumber:String;
    contactNumber:Number;
    email:String;
    enquiryDate:Date;
    dateOfBirth:Date;
    city:String;
    creditLimit:Number;
    lastUpdatedCreditDate:Date;
    applicationStatus:String;
    prospectAssetId:String
}
